### ISSUE TITLE
Multiuser Support Checklist

### ISSUE THREAD

**Issue by ApolloZhu** [UWRealityLab/xrcapstone22wi-team8#27]
From https://github.com/UWRealityLab/xrcapstone22wi-team8/pull/25#issue-1128052241 and https://github.com/UWRealityLab/xrcapstone22wi-team8/pull/25#issuecomment-1033399142

- [ ] The controller models and pen/eraser are shared between all players in a room rather than each player having their own. This is less of a concern for now because…
- [ ] Whiteboard drawings are not synchronized at all. I will implement this via RPC (rather than views) because its infeasible to transfer the textures over the network 10+ times per second.
- [ ] Users cannot enter their name before joining a room. I’m having trouble getting the onscreen keyboard to show up when a text input is focused, and it’s not so important because nameplates are not displayed yet either.
- [ ] Users do not have a model for their head or body.
- [ ] Users cannot leave rooms.
- [ ] Imported file contents are not networked at all.
- [ ] When joining a room fails the “Connecting…” message will remain on screen, rather than showing a failure message.
- [ ] AndroidLogcatSettings is still tracked despite added to `.gitignore`. Might want to delete the file
- [ ] Private/internal variable naming convention, e.g. multiuserScene -> _multiuserScene (see https://docs.microsoft.com/en-us/dotnet/csharp/fundamentals/coding-style/coding-conventions for the full style guide)

**Comment by ApolloZhu** [comment]
Problems

- [ ] The first player is not visible
- [ ] Drawing before joining are gone
- [ ] Initial brush state not sent out to later joined
